"""initial schema

Revision ID: 25e6a7d55948
Revises:
Create Date: 2026-08-06 15:47:17.547157+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "25e6a7d55948"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_competition_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column(
            "competition_type",
            sa.Enum(
                "league",
                "domestic_cup",
                "league_cup",
                "super_cup",
                "international_club",
                "international_national",
                "friendly",
                "other",
                name="competitiontype",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("is_competitive", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitions")),
        sa.UniqueConstraint(
            "provider_competition_id", name=op.f("uq_competitions_provider_competition_id")
        ),
    )
    op.create_index(
        "ix_competitions_country_type",
        "competitions",
        ["country", "competition_type"],
        unique=False,
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum(
                "competitions",
                "seasons",
                "teams",
                "fixtures",
                "lineups",
                "player_statistics",
                name="ingestionjobtype",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "partial",
                "failed",
                name="ingestionjobstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column(
            "parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("records_created", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_failed", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "error_details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_ingestion_jobs_finished_after_started"),
        ),
        sa.CheckConstraint(
            "records_created >= 0", name=op.f("ck_ingestion_jobs_records_created_non_negative")
        ),
        sa.CheckConstraint(
            "records_failed >= 0", name=op.f("ck_ingestion_jobs_records_failed_non_negative")
        ),
        sa.CheckConstraint(
            "records_processed >= 0", name=op.f("ck_ingestion_jobs_records_processed_non_negative")
        ),
        sa.CheckConstraint(
            "records_updated >= 0", name=op.f("ck_ingestion_jobs_records_updated_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
    )
    op.create_index(
        "ix_ingestion_jobs_job_type_created_at",
        "ingestion_jobs",
        ["job_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_jobs_status_created_at",
        "ingestion_jobs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_team_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("short_name", sa.String(length=60), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("search_name", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("provider_team_id", name=op.f("uq_teams_provider_team_id")),
    )
    op.create_index("ix_teams_search_name", "teams", ["search_name"], unique=False)
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_player_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("common_name", sa.String(length=150), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("primary_position", sa.String(length=60), nullable=True),
        sa.Column(
            "position_group",
            sa.Enum(
                "goalkeeper",
                "defender",
                "midfielder",
                "attacker",
                "unknown",
                name="positiongroup",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "preferred_foot",
            sa.Enum(
                "left",
                "right",
                "both",
                "unknown",
                name="preferredfoot",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("current_team_id", sa.Integer(), nullable=True),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("search_name", sa.String(length=200), nullable=False),
        sa.Column("search_common_name", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["current_team_id"],
            ["teams.id"],
            name=op.f("fk_players_current_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
        sa.UniqueConstraint("provider_player_id", name=op.f("uq_players_provider_player_id")),
    )
    op.create_index(
        op.f("ix_players_current_team_id"), "players", ["current_team_id"], unique=False
    )
    op.create_index(
        "ix_players_current_team_id_position_group",
        "players",
        ["current_team_id", "position_group"],
        unique=False,
    )
    op.create_index(
        "ix_players_search_common_name", "players", ["search_common_name"], unique=False
    )
    op.create_index("ix_players_search_name", "players", ["search_name"], unique=False)
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("season_year", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_seasons_end_after_start"),
        ),
        sa.CheckConstraint(
            "season_year BETWEEN 1850 AND 2200", name=op.f("ck_seasons_season_year_range")
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_seasons_competition_id_competitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint(
            "competition_id", "season_year", name=op.f("uq_seasons_competition_id_season_year")
        ),
    )
    op.create_index(op.f("ix_seasons_competition_id"), "seasons", ["competition_id"], unique=False)
    op.create_index("ix_seasons_is_current", "seasons", ["is_current"], unique=False)
    op.create_table(
        "fixtures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_fixture_id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("fixture_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "live",
                "finished",
                "postponed",
                "cancelled",
                "abandoned",
                "suspended",
                "unknown",
                name="fixturestatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("venue", sa.String(length=200), nullable=True),
        sa.Column("round", sa.String(length=100), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "away_score IS NULL OR away_score >= 0",
            name=op.f("ck_fixtures_away_score_non_negative"),
        ),
        sa.CheckConstraint(
            "home_score IS NULL OR home_score >= 0",
            name=op.f("ck_fixtures_home_score_non_negative"),
        ),
        sa.CheckConstraint("home_team_id <> away_team_id", name=op.f("ck_fixtures_distinct_teams")),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
            name=op.f("fk_fixtures_away_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_fixtures_competition_id_competitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
            name=op.f("fk_fixtures_home_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_fixtures_season_id_seasons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixtures")),
        sa.UniqueConstraint("provider_fixture_id", name=op.f("uq_fixtures_provider_fixture_id")),
    )
    op.create_index(
        "ix_fixtures_away_team_id_fixture_date",
        "fixtures",
        ["away_team_id", "fixture_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fixtures_competition_id"), "fixtures", ["competition_id"], unique=False
    )
    op.create_index(
        "ix_fixtures_competition_season_date",
        "fixtures",
        ["competition_id", "season_id", "fixture_date"],
        unique=False,
    )
    op.create_index("ix_fixtures_fixture_date", "fixtures", ["fixture_date"], unique=False)
    op.create_index(
        "ix_fixtures_home_team_id_fixture_date",
        "fixtures",
        ["home_team_id", "fixture_date"],
        unique=False,
    )
    op.create_index(op.f("ix_fixtures_season_id"), "fixtures", ["season_id"], unique=False)
    op.create_index("ix_fixtures_status", "fixtures", ["status"], unique=False)
    op.create_table(
        "player_fixture_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("opponent_id", sa.Integer(), nullable=False),
        sa.Column("home", sa.Boolean(), nullable=False),
        sa.Column("started", sa.Boolean(), nullable=False),
        sa.Column("substitute_appearance", sa.Boolean(), nullable=False),
        sa.Column("minutes_played", sa.Integer(), nullable=True),
        sa.Column("position", sa.String(length=60), nullable=True),
        sa.Column("shirt_number", sa.Integer(), nullable=True),
        sa.Column("shots", sa.Integer(), nullable=True),
        sa.Column("shots_on_target", sa.Integer(), nullable=True),
        sa.Column("goals", sa.Integer(), nullable=True),
        sa.Column("assists", sa.Integer(), nullable=True),
        sa.Column("key_passes", sa.Integer(), nullable=True),
        sa.Column("touches", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("team_shots", sa.Integer(), nullable=True),
        sa.Column("team_shots_on_target", sa.Integer(), nullable=True),
        sa.Column("early_exit", sa.Boolean(), nullable=True),
        sa.Column("data_source", sa.String(length=50), nullable=False),
        sa.Column(
            "data_quality_status",
            sa.Enum(
                "complete",
                "partial",
                "missing_sot",
                "missing_lineup",
                "provider_error",
                "manually_verified",
                name="dataqualitystatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "provider_raw_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "NOT (started AND substitute_appearance)",
            name=op.f("ck_player_fixture_stats_start_xor_substitute"),
        ),
        sa.CheckConstraint(
            "assists IS NULL OR assists >= 0",
            name=op.f("ck_player_fixture_stats_assists_non_negative"),
        ),
        sa.CheckConstraint(
            "goals IS NULL OR goals >= 0", name=op.f("ck_player_fixture_stats_goals_non_negative")
        ),
        sa.CheckConstraint(
            "minutes_played IS NULL OR (minutes_played >= 0 AND minutes_played <= 200)",
            name=op.f("ck_player_fixture_stats_minutes_played_range"),
        ),
        sa.CheckConstraint(
            "rating IS NULL OR (rating >= 0 AND rating <= 10)",
            name=op.f("ck_player_fixture_stats_rating_range"),
        ),
        sa.CheckConstraint(
            "shots IS NULL OR shots >= 0", name=op.f("ck_player_fixture_stats_shots_non_negative")
        ),
        sa.CheckConstraint(
            "shots IS NULL OR shots_on_target IS NULL OR shots_on_target <= shots",
            name=op.f("ck_player_fixture_stats_shots_on_target_within_shots"),
        ),
        sa.CheckConstraint(
            "shots_on_target IS NULL OR shots_on_target >= 0",
            name=op.f("ck_player_fixture_stats_shots_on_target_non_negative"),
        ),
        sa.CheckConstraint(
            "team_id <> opponent_id",
            name=op.f("ck_player_fixture_stats_distinct_team_and_opponent"),
        ),
        sa.CheckConstraint(
            "team_shots_on_target IS NULL OR team_shots IS NULL OR team_shots_on_target <= team_shots",
            name=op.f("ck_player_fixture_stats_team_sot_within_team_shots"),
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_player_fixture_stats_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opponent_id"],
            ["teams.id"],
            name=op.f("fk_player_fixture_stats_opponent_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_player_fixture_stats_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_player_fixture_stats_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_fixture_stats")),
        sa.UniqueConstraint(
            "fixture_id",
            "player_id",
            "team_id",
            name=op.f("uq_player_fixture_stats_fixture_id_player_id_team_id"),
        ),
    )
    op.create_index(
        "ix_player_fixture_stats_data_quality_status",
        "player_fixture_stats",
        ["data_quality_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_fixture_stats_fixture_id"),
        "player_fixture_stats",
        ["fixture_id"],
        unique=False,
    )
    op.create_index(
        "ix_player_fixture_stats_opponent_started",
        "player_fixture_stats",
        ["opponent_id", "started"],
        unique=False,
    )
    op.create_index(
        "ix_player_fixture_stats_player_sot",
        "player_fixture_stats",
        ["player_id", "shots_on_target"],
        unique=False,
    )
    op.create_index(
        "ix_player_fixture_stats_player_started_home",
        "player_fixture_stats",
        ["player_id", "started", "home"],
        unique=False,
    )
    op.create_index(
        "ix_player_fixture_stats_team_started",
        "player_fixture_stats",
        ["team_id", "started"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_player_fixture_stats_team_started", table_name="player_fixture_stats")
    op.drop_index("ix_player_fixture_stats_player_started_home", table_name="player_fixture_stats")
    op.drop_index("ix_player_fixture_stats_player_sot", table_name="player_fixture_stats")
    op.drop_index("ix_player_fixture_stats_opponent_started", table_name="player_fixture_stats")
    op.drop_index(op.f("ix_player_fixture_stats_fixture_id"), table_name="player_fixture_stats")
    op.drop_index("ix_player_fixture_stats_data_quality_status", table_name="player_fixture_stats")
    op.drop_table("player_fixture_stats")
    op.drop_index("ix_fixtures_status", table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_season_id"), table_name="fixtures")
    op.drop_index("ix_fixtures_home_team_id_fixture_date", table_name="fixtures")
    op.drop_index("ix_fixtures_fixture_date", table_name="fixtures")
    op.drop_index("ix_fixtures_competition_season_date", table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_competition_id"), table_name="fixtures")
    op.drop_index("ix_fixtures_away_team_id_fixture_date", table_name="fixtures")
    op.drop_table("fixtures")
    op.drop_index("ix_seasons_is_current", table_name="seasons")
    op.drop_index(op.f("ix_seasons_competition_id"), table_name="seasons")
    op.drop_table("seasons")
    op.drop_index("ix_players_search_name", table_name="players")
    op.drop_index("ix_players_search_common_name", table_name="players")
    op.drop_index("ix_players_current_team_id_position_group", table_name="players")
    op.drop_index(op.f("ix_players_current_team_id"), table_name="players")
    op.drop_table("players")
    op.drop_index("ix_teams_search_name", table_name="teams")
    op.drop_table("teams")
    op.drop_index("ix_ingestion_jobs_status_created_at", table_name="ingestion_jobs")
    op.drop_index("ix_ingestion_jobs_job_type_created_at", table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_index("ix_competitions_country_type", table_name="competitions")
    op.drop_table("competitions")
    # ### end Alembic commands ###
