"""Autogenerate filters shared by ``alembic/env.py`` and the migration tests.

Kept in one place so the migration environment and the drift test cannot
disagree about which schema objects Alembic is responsible for.
"""

from __future__ import annotations

from collections.abc import Callable

from sqlalchemy import CheckConstraint, MetaData

#: Alembic's own bookkeeping table, never part of a migration.
ALEMBIC_VERSION_TABLE = "alembic_version"


def type_bound_check_constraint_names(metadata: MetaData) -> frozenset[str]:
    """Names of CHECK constraints generated by a column *type*.

    ``Enum(create_constraint=True)`` attaches a CHECK constraint to the table
    with ``_type_bound = True``.  These are emitted automatically whenever the
    column is created, so they must not be compared as standalone objects.

    Alembic's check-constraint comparison does not exclude them, and reflected
    constraints carry no ``_type_bound`` marker to match on - so both sides are
    filtered by *name*, which is identical in metadata and in the database.
    """
    names: set[str] = set()
    for table in metadata.tables.values():
        for constraint in table.constraints:
            if (
                isinstance(constraint, CheckConstraint)
                and getattr(constraint, "_type_bound", False)
                and constraint.name is not None
            ):
                names.add(str(constraint.name))
    return frozenset(names)


def make_include_object(
    metadata: MetaData,
) -> Callable[[object, str | None, str, bool, object], bool]:
    """Build the ``include_object`` hook for Alembic autogenerate.

    Without the type-bound filter, every ``--autogenerate`` run would emit a
    migration dropping and recreating each enum CHECK constraint - and a
    reviewer who applied it would lose that validation from the database.
    """
    type_bound_names = type_bound_check_constraint_names(metadata)

    def include_object(
        obj: object,
        name: str | None,
        type_: str,
        reflected: bool,
        compare_to: object,
    ) -> bool:
        if type_ == "table" and name == ALEMBIC_VERSION_TABLE:
            return False
        return name not in type_bound_names

    return include_object
